/*
 * This file was generated by generate_typesystem.py.
 */
#ifndef __RS_KBREASONING_ALL_TYPES_H__
#define __RS_KBREASONING_ALL_TYPES_H__

#include <rs_kbreasoning/types/type_definitions.h>


#endif /* __RS_KBREASONING_ALL_TYPES_H__ */
